name: EURO-AUD

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  http_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make HTTP GET request
        env: 
          FREECURRENCYAPI: ${{ secrets.FREECURRENCYAPI }}      
        run: |
          # Make the HTTP GET request and save it to a JSON file with a timestamp in the filename
          # timestamp="$(date +'%Y%m%d%H%M%S')"
          # curl -s -o "${timestamp}.json" "https://api.freecurrencyapi.com/v1/latest?apikey=${FREECURRENCYAPI}&currencies=EUR&base_currency=AUD"
          # ls -lrt
          # cat "${timestamp}.json"
          pip install matplotlib
          python plot.py
          
      - name: Commit changes
        run: |
          git config --global user.email "s50600822@gmail.com"
          git config --global user.name "s50600822"
          git add .
          git commit -m "save"
          git push
