name: EURO-AUD

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  http_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make HTTP GET request
        env: 
          FREECURRENCYAPI: ${{ secrets.FREECURRENCYAPI }}      
        run: |
          # Make the HTTP GET request and save it to a JSON file with a timestamp in the filename
          timestamp="$(date +'%Y%m%d%H%M%S')"
          curl -s -o "${timestamp}.json" "https://api.freecurrencyapi.com/v1/latest?apikey=${FREECURRENCYAPI}&currencies=EUR&base_currency=AUD"
          ls -lrt
          cat "${timestamp}.json"

      - name: Commit changes
        env: 
          PAT: ${{ secrets.PAT }}      
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global credential.helper store
          echo "https://github.com ${PAT}:x-oauth-basic" > ~/.git-credentials          
          git add .
          git commit -m "Update JSON file [skip ci]"
          git push
